---
title: "01_QualityTrimming.Rmd"
output: html_document
date: "2026-03-04"
---

```{r setup-Rmd}
knitr::opts_chunk$set(echo = TRUE,
                       fig.align = "center", 
                       fig.path = "../figures/01_QualityTrimming")
```

#Set up the Environment

## Seeting the Seed

```{r set-seed}
set.seed(238428)
```

## Load libraries
```{r}
#Install Pacman
install.packages("pacman")
library(pacman)
pacman::p_load(
  tidyverse,
  dada2,
  patchwork,
  Biostrings,
  ShortRead,
  install = TRUE)

pacman::p_load(tidyverse, dada2, patchwork, 
               Biostrings, ShortRead,
               install = FALSE)
```

# Read raw seqeunces
```{r read-fastq}
#set the path to raw seq files
raw_fastqs_path <- "data/00_raw_gzipped_fastqs"
raw_fastqs_path

# What files are in this path? Intuition Check 
head(list.files(raw_fastqs_path))
# How many files are in this path? Intuition Check 
length(list.files(raw_fastqs_path))


# create vector of Forward Reads, ending with "R1_001.fastq.gz"
forward_reads <- list.files(raw_fastqs_path, pattern = "R1_001.fastq.gz", full.names = TRUE)
head(forward_reads)

# create vectors of Reverse Reads
# Intuition check #2: We should have fewer reads in the forward vector than in total 
stopifnot(length(forward_reads) < length(list.files(raw_fastqs_path)))

# Create a vector of reverse reads 
reverse_reads <- list.files(raw_fastqs_path, pattern = "R2_001.fastq.gz", full.names = TRUE)

# Intuition Checks
head(reverse_reads)

# Intuition check #2: Need to have equal number of forward and reverse files 
stopifnot(length(reverse_reads) == length(forward_reads))

```

```{r Raw Read Quality}
random_samples <- sample(1:length(reverse_reads), size = 12)

# plot forward read quality
forward_rawQual_plot12 <- plotQualityProfile(forward_reads[random_samples]) +
  labs(title = 'Forward Reads: Raw Quality')

# plot reverse read quality
reverse_rawQual_plot12 <- plotQualityProfile(reverse_reads[random_samples]) +
  labs(title = 'Reverse Reads: Raw Quality')

# plot both together
forward_rawQual_plot12 + reverse_rawQual_plot12
```

```{r prep-filtTrim}
# Create vector of sample names
sample_names <- sapply(strsplit(basename(forward_reads), "_"), `[`, 1)

#basename remove the file direcotry only show the file name
#strsplit function seperate the string based on given criteria, which here is the "_"
sample_names_R2 <- sapply(strsplit(basename(reverse_reads), "_"), `[`, 1)

# create a test of the sample names
# stopifnot: highlight the content in the bracket to compare
stopifnot(sample_names == sample_names_R2)

#test
head(sample_names)

# Provide path for the filtered reads
filtered_fastqs_path <- "data/01-QualityTrimming/filtered_fastqs"
filtered_fastqs_path

# create 2 vectors filtered_forward_reads and filtered_reverse_reads
filtered_forward_reads <- file.path (filtered_fastqs_path, paste0(sample_names, "_R1_filtered.fastq.gz"))

  #intuition check
length(filtered_forward_reads)


filtered_reverse_reads <- file.path (filtered_fastqs_path, paste0(sample_names, "_R2_filtered.fastq.gz"))

  #intuition check
length(filtered_reverse_reads)
```

```{r Filtering & Trimming}
#trimming parameters are global for a dataset, shorter ASV cannot be compared to the longer ASV
filtered_reads <- 
  filterAndTrim(fwd = forward_reads, filt = filtered_forward_reads,
                rev = reverse_reads, filt.rev = filtered_reverse_reads,
                #run the filtering
                maxN = 0, maxEE = c(2,2), truncQ = 2,
                # trim 
                trimLeft = c(8,3), truncLen = c(250, 248),
                rm.phix = TRUE, compress = TRUE,
                multithread = 12)

```


